version: '3.9'

services:

  admin:
    container_name: ${APP_NAME}-admin
    build:
      context: ./admin
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./admin:/usr/src/app/adminapp
      - /usr/src/app/adminapp/node_modules
    environment:
      - VIRTUAL_HOST=admin.insset.localhost
      - VIRTUAL_PORT=4000
    networks:
      - proxy

  students:
    container_name: ${APP_NAME}-students
    build:
      context: ./students
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./students:/usr/src/app/studentsapp
      - /usr/src/app/studentsapp/node_modules
    environment:
      - VIRTUAL_HOST=students.insset.localhost
      - VIRTUAL_PORT=3000
    networks:
      - proxy

  backend:
    container_name: ${APP_NAME}-backend
    build:
      context: ./backend
      args:
        - USER=gestproj
        - UID=1000
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=api.insset.localhost
      - VIRTUAL_PORT=5000
    volumes:
      - ./backend/data:/home/gestproj/data
      - ./backend/gplib:/home/gestproj/gplib
      - ./backend/cli:/home/gestproj/cli
      - ./backend/api:/home/gestproj/api
      - ./backend/ovh:/home/gestproj/ovh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
