version: '3.9'

services:

  admin:
    container_name: ${APP_NAME}-admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$TRAEFIK_KEY-admin-web.rule=host(`admin.insset.localhost`)"
    build:
      context: ./admin
    networks:
      traefik:
        ipv4_address: 172.10.0.3

  students:
    container_name: ${APP_NAME}-students
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$TRAEFIK_KEY-students-web.rule=host(`students.insset.localhost`)"
    build:
      context: ./students
    networks:
      traefik:
        ipv4_address: 172.10.0.4

  backend:
    container_name: ${APP_NAME}-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$TRAEFIK_KEY-backend-web.rule=host(`backend.insset.localhost`)"
      - "traefik.http.services.$TRAEFIK_KEY-backend-service.loadbalancer.server.port=5000"
    build:
      context: ./backend
    ports:
      - "2222:22"
    volumes:
      - ./work:/home/gestproj/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./home:/home/etudiants
      - ./backend/cli:/home/gestproj/cli
      - ./backend/gplib:/home/gestproj/gplib
      - ./backend/config/docker-skell:/home/gestproj/docker-skell
    networks:
      traefik:
        ipv4_address: 172.10.0.5

volumes:
  backendData: {}
