version: '3.9'

services:

  traefik:
    command:
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --entrypoints.websecure.http.tls.domains[0].main=$DOMAIN
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAIN
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  grafana:
    labels:
      - "traefik.http.routers.$TRAEFIK_KEY-grafana-web.entrypoints=web"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana-web.entrypoints=web"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana-web.middlewares=redirect-to-https"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana.tls=true"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana.rule=Host(`grafana.$HOST`)"
      - "traefik.http.routers.$TRAEFIK_KEY-grafana.entrypoints=websecure"

  admin:
    labels:
      - "traefik.http.routers.$TRAEFIK_KEY-admin-web.entrypoints=web"
      - "traefik.http.routers.$TRAEFIK_KEY-admin-web.middlewares=redirect-to-https"
      - "traefik.http.routers.$TRAEFIK_KEY-admin.tls=true"
      - "traefik.http.routers.$TRAEFIK_KEY-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$TRAEFIK_KEY-admin.rule=Host(`admin.$HOST`)"
      - "traefik.http.routers.$TRAEFIK_KEY-admin.entrypoints=websecure"

  students:
    labels:
      - "traefik.http.routers.$TRAEFIK_KEY-students-web.entrypoints=web"
      - "traefik.http.routers.$TRAEFIK_KEY-students-web.middlewares=redirect-to-https"
      - "traefik.http.routers.$TRAEFIK_KEY-students.tls=true"
      - "traefik.http.routers.$TRAEFIK_KEY-students.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$TRAEFIK_KEY-students.rule=Host(`students.$HOST`)"
      - "traefik.http.routers.$TRAEFIK_KEY-students.entrypoints=websecure"

  backend:
    labels:
      - "traefik.http.routers.$TRAEFIK_KEY-backend-web.entrypoints=web"
      - "traefik.http.routers.$TRAEFIK_KEY-backend-web.middlewares=redirect-to-https"
      - "traefik.http.routers.$TRAEFIK_KEY-backend.tls=true"
      - "traefik.http.routers.$TRAEFIK_KEY-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$TRAEFIK_KEY-backend.rule=Host(`backend.$HOST`)"
      - "traefik.http.routers.$TRAEFIK_KEY-backend.entrypoints=websecure"