name: Build / Push Admin

# This workflow deploy the Admin Panel
# @author Fragan
# @version 0.1.0

on:
  push:
    branches: ['feature/**', 'hotfix/**', 'develop', 'main']

jobs:

  # Build & Push the Docker image from the admin panel
  docker:
    uses: ./.github/workflows/DOCKER.yaml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './admin'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      target: 'production'
      registry: ghcr.io
      image_name: kraken-admin
