name: Build / Push Backend

# This workflow deploy the GestProj Backend
# @author Fragan
# @version 0.1.0

on:
  push:
    branches: ['feature/**', 'develop', 'main']

jobs:

  # Build & Push the Docker image from the backend
  build-and-push-image:
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './backend'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      registry: ghcr.io
      image_name: ${{ github.repository }}-backend
