name: Build / Push Backend

# This workflow deploy the Admin Panel
# @author Fragan
# @version 0.1.0

on:
  push:
    branches: ['feature/**', 'hotfix/**', 'develop', 'main']

jobs:

  # Run every required checking (lint, build, sonar, etc...)

  flask-cli:
    uses: ./.github/workflows/FLASK.yaml
    with:
      workdir: './backend/cli'

  flask-backend:
    uses: ./.github/workflows/FLASK.yaml
    with:
      workdir: './backend/backend'

  flask-api:
    uses: ./.github/workflows/FLASK.yaml
    with:
      workdir: './backend/api'

  sonarqube:
    uses: ./.github/workflows/SONARQUBE.yaml
    with:
      workdir: './backend'

  # Build & Push the Docker image from the admin panel
  docker:
    needs: ['flask', 'sonarqube']
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './backend'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      registry: ghcr.io
      image_name: kraken-backend
