name: Deploy release

on:
  push:
    branches: ['main']
  workflow_call:
    secrets:
      token:
        required: false
      PRIVATE_KEY:
        required: true
      SSH_USER:
        required: true
      SSH_HOST:
        required: true

jobs:

  admin:
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './admin'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      registry: ghcr.io
      image_name: ${{ github.repository }}-admin

  students:
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './students'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      registry: ghcr.io
      image_name: ${{ github.repository }}-students

  backend:
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './backend'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      registry: ghcr.io
      image_name: ${{ github.repository }}-backend

  deploy-to-production:
    needs: ['admin', 'students', 'backend']
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upgrade projet from remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/fragan/gestproj/src
            git pull
            docker compose -f docker-compose.dev.yml up -d --build