# @author Fragan
# @version 0.1.0
name: SonarQube Workflow

on:
  workflow_call:

jobs:

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: a3d5ea3bd83242bdc14a4f526ff8222946ce406e
