name: Build / Push Students

# This workflow deploy the Students Panel
# @author Fragan
# @version 0.1.0

on:
  push:
    branches: ['feature/**', 'hotfix/**', 'develop']

jobs:

  # Run every required checking (lint, build, sonar, etc...)
  vue:
    uses: ./.github/workflows/VUE.yaml
    with:
      workdir: './students'

  # Build & Push the Docker image from the student panel
  docker:
    needs: ['vue']
    uses: ./.github/workflows/DOCKER.yaml
    with:
      # Dockerfile build entry point (see. https://docs.docker.com/engine/context/working-with-contexts/)
      context: './students'
      # Dockerfile build target (see. https://docs.docker.com/develop/develop-images/multistage-build/)
      target: 'production'
      registry: ghcr.io
      image_name: ${{ github.repository }}-students
