name: Vue.Js Workflow

# This workflow check the code of a Vue.Js application
# @author Fragan
# @version 0.1.0

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:

  cache-build:
    name: Build - With Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: cd ${{ inputs.workdir }} && npm install
      - run: cd ${{ inputs.workdir }} && npm run build
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./${{ inputs.workdir }}/*
          key: ${{ github.sha }}

  vue-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./${{ inputs.workdir }}/*
          key: ${{ github.sha }}
      - run: |
          npm run lint

  vue-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./${{ inputs.workdir }}/*
          key: ${{ github.sha }}
      - run: |
          npm run test:unit
