name: Lint Vue.js

# This workflow check the code of a Vue.Js application
# @author Fragan
# @version 0.1.0

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ${{ inputs.workdir }}
          npm install
          npm run lint
